# Generated by Django 6.0.7 on 2026-07-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('holdings_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_worth', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
